# Generated by Django 4.2 on 2025-08-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_address_user_city_user_fullname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="City",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="FullName",
            new_name="full_name",
        ),
    ]
