# Generated by Django 4.2 on 2025-07-19 20:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth_cdccd", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CDEmployee",
            new_name="CDUser",
        ),
    ]
