version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lfras_phone_web
    command: python manage.py runserver 0.0.0.0:2225
    volumes:
      - .:/app
    ports:
      - "2225:2225"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: lfras_phone_db
    restart: always
    environment:
      POSTGRES_DB: lfras_db
      POSTGRES_USER: lfras_user
      POSTGRES_PASSWORD: Xunil@999
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: