# Generated by Django 5.0.6 on 2025-08-11 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.PositiveIntegerField(db_index=True)),
                ("customer_id", models.PositiveIntegerField(db_index=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[("expiry", "Expiry Reminder"), ("custom", "Custom")],
                        db_index=True,
                        default="expiry",
                        max_length=32,
                    ),
                ),
                ("template_key", models.CharField(db_index=True, max_length=255)),
                ("subject_template", models.TextField(blank=True, default="")),
                ("body_template", models.TextField(blank=True, default="")),
                ("s3_key", models.CharField(blank=True, default="", max_length=1024)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["template_type", "template_key"],
                "unique_together": {("client_id", "customer_id", "template_key")},
            },
        ),
        migrations.CreateModel(
            name="ConfigFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.PositiveIntegerField(db_index=True)),
                ("customer_id", models.PositiveIntegerField(db_index=True)),
                ("file_name", models.CharField(max_length=255)),
                ("s3_key", models.CharField(db_index=True, max_length=1024)),
                ("content_type", models.CharField(default="text/plain", max_length=64)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("client_id", "customer_id", "file_name")},
            },
        ),
    ]
