# Generated by Django 4.2 on 2025-07-19 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("OTP_SENT", "OTP Sent"),
                            ("OTP_FAILED", "OTP Failed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                            ("ACTIVITY_STARTED", "Activity Started"),
                            ("FILE_UPLOADED", "File Uploaded"),
                            ("FILE_VALIDATED", "File Validated"),
                            ("ACTIVITY_COMPLETED", "Activity Completed"),
                            ("REPORT_REQUESTED", "Report Requested"),
                            ("REPORT_GENERATED", "Report Generated"),
                            ("REPORT_DOWNLOADED", "Report Downloaded"),
                            ("TICKET_CREATED", "Ticket Created"),
                            ("TICKET_UPDATED", "Ticket Updated"),
                            ("TICKET_COMMENT_ADDED", "Ticket Comment Added"),
                            ("TICKET_CLOSED", "Ticket Closed"),
                            ("NOTIFICATION_TRIGGERED", "Notification Triggered"),
                            ("NOTIFICATION_SENT", "Notification Sent"),
                            ("NOTIFICATION_SEEN", "Notification Seen"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cd_id", models.UUIDField(blank=True, null=True)),
                ("ccd_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
