# Generated by Django 5.0.6 on 2025-08-11 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("cc_email", models.EmailField(blank=True, default="", max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "template_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("context_json", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["to_email", "sent_at"],
                        name="emails_emai_to_emai_d85277_idx",
                    )
                ],
            },
        ),
    ]
