# Generated by Django 4.2 on 2025-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcd",
            name="smtp_config",
            field=models.JSONField(default=dict),
        ),
    ]
