# Generated by Django 5.0.6 on 2025-08-11 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.PositiveIntegerField(db_index=True)),
                (
                    "customer_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number in E.164 format, e.g. +14155552671.",
                                regex="^\\+[1-9]\\d{7,14}$",
                            )
                        ],
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                ("address", models.CharField(blank=True, default="", max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_id"], name="customers_client__86a1b6_idx"
                    ),
                    models.Index(fields=["email"], name="customers_email_92e882_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("client_id", "email"), name="uniq_customer_email_per_client"
            ),
        ),
    ]
