# Generated by Django 5.0.6 on 2025-08-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.PositiveBigIntegerField(db_index=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("downloads", "Downloads"),
                            ("users", "Users"),
                            ("customers", "Customers"),
                            ("activities", "Activities"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "requested_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("pdf", "PDF"),
                            ("txt", "Text"),
                        ],
                        default="csv",
                        max_length=8,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("HALF_YEARLY", "Half-yearly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reports_scheduled_reports",
                "indexes": [
                    models.Index(
                        fields=["client_id", "active"],
                        name="reports_sch_client__9043f2_idx",
                    ),
                    models.Index(
                        fields=["next_run_at"], name="reports_sch_next_ru_eb143a_idx"
                    ),
                ],
            },
        ),
    ]
